repos:
  - repo: git@github.com:timothycrosley/isort.git
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

  - repo: git@github.com:psf/black.git
    rev: 24.10.0
    hooks:
      - id: black
